/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Aplicacao: () => import('#controllers/aplicacao_controller'),
  Clientes: () => import('#controllers/clientes_controller'),
  Contas: () => import('#controllers/contas_controller'),
  Extrato: () => import('#controllers/extrato_controller'),
  Pix: () => import('#controllers/pix_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
